// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-tag': string;
  'tag-selector': string;
  'trigger': string;
}
export const cssExports: CssExports;
export default cssExports;
