// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit-tag': string;
  'site-tag-plus': string;
  'tag-input': string;
}
export const cssExports: CssExports;
export default cssExports;
